[package]
name = "zisk-tx-proof"
version = "0.1.0"
edition = "2021"

[dependencies]
# ZisK SDK for input/output
zisk-sdk = { git = "https://github.com/0xPolygonHermez/zisk.git" }

# Cryptographic dependencies
sha2 = { version = "0.10", default-features = false }

[features]
default = []